$(document).ready(function(){
    var i = 2;
    $("#x80").click(function(){
        $("#mdX80").modal()
    })
    $("#y15").click(function(){
        $("#mdY15").modal()
    })
    $("#v23e").click(function(){
        $("#mdV23e").modal()
    })
    $("#v25e").click(function(){
        $("#mdV25e").modal()
    })
    $("#y22").click(function(){
        $("#mdY22").modal()
    })
    $("#y228").click(function(){
        $("#mdY228").modal()
    })
    $("#y33").click(function(){
        $("#mdY33").modal()
    })
    $("#y01").click(function(){
        $("#mdY01").modal()
    })
    $("#i14PM").click(function(){
        $("#mdI14PM").modal()
    })
    $("#i14P").click(function(){
        $("#mdI14P").modal()
    })
    $("#i14Pl").click(function(){
        $("#mdI14Pl").modal()
    })
    $("#i14").click(function(){
        $("#mdI14").modal()
    })
    $("#i13").click(function(){
        $("#mdI13").modal()
    })
    $("#i11").click(function(){
        $("#mdI11").modal()
    })
    $("#i13PM").click(function(){
        $("#mdI13PM").modal()
    })
    $("#i13M").click(function(){
        $("#mdI13M").modal()
    })
    $("#sZF4").click(function(){
        $("#mdSZF4").modal()
    })
    $("#s22").click(function(){
        $("#mdS22").modal()
    })
    $("#sZ3").click(function(){
        $("#mdSZ3").modal()
    })
    $("#sZ4").click(function(){
        $("#mdSZ4").modal()
    })
    $("#sA23").click(function(){
        $("#mdSA23").modal()
    })
    $("#sS22").click(function(){
        $("#mdSS22").modal()
    })
    $("#sZF3").click(function(){
        $("#mdSZF3").modal()
    })
    $("#sM33").click(function(){
        $("#mdSM33").modal()
    })
    $("#oFX5").click(function(){
        $("#mdOFX5").modal()
    })
    $("#oR6").click(function(){
        $("#mdOR6").modal()
    })
    $("#oR7").click(function(){
        $("#mdOR7").modal()
    })
    $("#oR8").click(function(){
        $("#mdOR8").modal()
    })
    $("#oA96").click(function(){
        $("#mdOA96").modal()
    })
    $("#oA57").click(function(){
        $("#mdOA57").modal()
    })
    $("#oA77").click(function(){
        $("#mdOA77").modal()
    })
    $("#oA17").click(function(){
        $("#mdOA17").modal()
    })
    $("#r9").click(function(){
        $("#mdR9").modal()
    })
    $("#r8").click(function(){
        $("#mdR8").modal()
    })
    $("#rC30").click(function(){
        $("#mdRC30").modal()
    })
    $("#rC33").click(function(){
        $("#mdRC33").modal()
    })
    $("#r9i").click(function(){
        $("#mdR9i").modal()
    })
    $("#rC35").click(function(){
        $("#mdRC35").modal()
    })
    $("#rC25Y").click(function(){
        $("#mdRC25Y").modal()
    })
    $("#rC21Y").click(function(){
        $("#mdRC21Y").modal()
    })
    $("#chat").click(function(){
        $("#mdChat").modal()
    })
    $("#bdChat").click(function(){
        $("#mdbdChat").modal()
    })
    $("#xRN11").click(function(){
        $("#mdXRN11").modal()
    })
    $("#xRN11S").click(function(){
        $("#mdXRN11S").modal()
    })
    $("#x12").click(function(){
        $("#mdX12").modal()
    })
    $("#x11L").click(function(){
        $("#mdX11L").modal()
    })
    $("#x11P").click(function(){
        $("#mdX11P").modal()
    })
    $("#x12T").click(function(){
        $("#mdX12T").modal()
    })
    $("#xA1").click(function(){
        $("#mdXA1").modal()
    })
    $("#x9C").click(function(){
        $("#mdX9C").modal()
    })

})
